2024-07-30 17:43:46,701 INFO    MainThread:73882 [wandb_setup.py:_flush():76] Current SDK version is 0.17.5
2024-07-30 17:43:46,701 INFO    MainThread:73882 [wandb_setup.py:_flush():76] Configure stats pid to 73882
2024-07-30 17:43:46,701 INFO    MainThread:73882 [wandb_setup.py:_flush():76] Loading settings from /Users/zave/.config/wandb/settings
2024-07-30 17:43:46,701 INFO    MainThread:73882 [wandb_setup.py:_flush():76] Loading settings from /Users/zave/Private/dev/learning/aiffel-research/mlops/node/mle_part_2/wandb/settings
2024-07-30 17:43:46,701 INFO    MainThread:73882 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-07-30 17:43:46,701 INFO    MainThread:73882 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-30 17:43:46,701 INFO    MainThread:73882 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'mlops/node/mle_part_2/load_model_from_wandb.py', 'program_abspath': '/Users/zave/Private/dev/learning/aiffel-research/mlops/node/mle_part_2/load_model_from_wandb.py', 'program': '/Users/zave/Private/dev/learning/aiffel-research/mlops/node/mle_part_2/load_model_from_wandb.py'}
2024-07-30 17:43:46,701 INFO    MainThread:73882 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-30 17:43:46,701 INFO    MainThread:73882 [wandb_init.py:_log_setup():529] Logging user logs to /Users/zave/Private/dev/learning/aiffel-research/mlops/node/mle_part_2/wandb/run-20240730_174346-mqfsgia8/logs/debug.log
2024-07-30 17:43:46,701 INFO    MainThread:73882 [wandb_init.py:_log_setup():530] Logging internal logs to /Users/zave/Private/dev/learning/aiffel-research/mlops/node/mle_part_2/wandb/run-20240730_174346-mqfsgia8/logs/debug-internal.log
2024-07-30 17:43:46,701 INFO    MainThread:73882 [wandb_init.py:init():569] calling init triggers
2024-07-30 17:43:46,702 INFO    MainThread:73882 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {}
2024-07-30 17:43:46,702 INFO    MainThread:73882 [wandb_init.py:init():619] starting backend
2024-07-30 17:43:46,702 INFO    MainThread:73882 [wandb_init.py:init():623] setting up manager
2024-07-30 17:43:46,705 INFO    MainThread:73882 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-07-30 17:43:46,706 INFO    MainThread:73882 [wandb_init.py:init():631] backend started and connected
2024-07-30 17:43:46,709 INFO    MainThread:73882 [wandb_init.py:init():720] updated telemetry
2024-07-30 17:43:46,724 INFO    MainThread:73882 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-07-30 17:43:47,336 INFO    MainThread:73882 [wandb_run.py:_on_init():2435] communicating current version
2024-07-30 17:43:47,427 INFO    MainThread:73882 [wandb_run.py:_on_init():2444] got version response 
2024-07-30 17:43:47,428 INFO    MainThread:73882 [wandb_init.py:init():804] starting run threads in backend
2024-07-30 17:43:48,634 WARNING MainThread:73882 [wandb_init.py:init():1185] interrupted
Traceback (most recent call last):
  File "/Users/zave/anaconda3/envs/aiffel-research/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    return wi.init()
  File "/Users/zave/anaconda3/envs/aiffel-research/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 817, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/Users/zave/anaconda3/envs/aiffel-research/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/zave/anaconda3/envs/aiffel-research/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/zave/anaconda3/envs/aiffel-research/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/Users/zave/anaconda3/envs/aiffel-research/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/zave/anaconda3/envs/aiffel-research/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-07-30 17:43:54,230 WARNING MsgRouterThr:73882 [router.py:message_loop():77] message_loop has been closed
